name: Deploy React Frontend

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

permissions:
  contents: write  # Allow the action to push to the repository

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Build React app
        working-directory: ./client
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/build